### ISSUE TITLE
About Environment

### ISSUE THREAD

**Issue by YingZ000** [Wert1996/Traffic-Optimisation#2]
I want to run this project on windows. But there is one path cannot be changed.
Please.
_______________________________________________________________________________________________________
Loading configuration... done.
Error: Could not build output file '/home/wert/Documents/development/Traffic-Optimisation/data/resultsOfDetectors.xml' (No such file or directory).
......
Error: Could not build output file '/home/wert/Documents/development/Traffic-Optimisation/data/resultsOfDetectors.xml' (No such file or directory).
Quitting (on error).

**Comment by YingZ000** [comment]
I got it！
I changed it in bangalore.det.xml

Thanks for your sharing and your great work.

**Comment by Wert1996** [comment]
Thanks! :)
Feel free to make any improvements :)
